### ISSUE TITLE
First index change is broken

### ISSUE THREAD

**Issue by nikandlv** [oliviertassinari/react-swipeable-views#599]
The first time you change the index it won't animate.
Here's a demo https://material-ui.com/components/tabs/#full-width

**Comment by oliviertassinari** [comment]
Wrong repo.

**Comment by eprice122** [comment]
Bug present in Chrome but not FireFox

**Comment by peitalin** [comment]
The bug is present on:
Chrome v83
Firefox v77
Safari v12

Any idea where in the codebase to start looking at fixing this?
I would like to take a look.
@oliviertassinari

**Comment by peitalin** [comment]
Did some digging,

When the component first mounts, [`displaySameSlide](https://github.com/oliviertassinari/react-swipeable-views/blob/8f3d3a14cd37a870c50deda67b26791d80ff04fd/packages/react-swipeable-views/src/SwipeableViews.js#L247)` is initially `true`,
causing transition = “all 0s ease 0s” when component first mounts.

![image](https://user-images.githubusercontent.com/4037878/85396133-8aff5d00-b594-11ea-892d-8a7eecff8ae4.png)

Then after the 1st transition, the computed `displaySameSlide` = `false` (calculated in [`componentsWillReceiveProps`](https://github.com/oliviertassinari/react-swipeable-views/blob/8f3d3a14cd37a870c50deda67b26791d80ff04fd/packages/react-swipeable-views/src/SwipeableViews.js#L315)), after which the calculated transition = “transform 0.35s cubix-bezier(0.15, 0.3, 0.25, 1) 0s”
which enables the transition animation thereafter.

![image](https://user-images.githubusercontent.com/4037878/85396403-06610e80-b595-11ea-8b84-ebfa3d2de36b.png)

**Comment by lord0gnome** [comment]
Hi! Is there any word on progress to this? Quite annoying! Thanks for the library either way, it's great!

**Comment by I3rendan** [comment]
This is not a perfect solution, but if you take advantage of the `containerStyle` property you can get the initial slide to transition correctly...

```
<SwipeableViews
    containerStyle={{
        transition: 'transform 0.35s cubic-bezier(0.15, 0.3, 0.25, 1) 0s'
    }}
    ...
```

**Comment by lord0gnome** [comment]
Ah, Thank you very much!!! Works like a charm, true that it is imperfect but so is my application so I can't judge it. XD

**Comment by nikandlv** [comment]
@I3rendan its a good workaround till the pull request is merged

**Comment by sdutwsl** [comment]
the bug is still existing on Chrome 85.0

**Comment by kahirokunn** [comment]
the bug is still existing on Chrome 86

**Comment by Meet008** [comment]
issue still not resolved with chrome. please fix it.

**Comment by oliviertassinari** [comment]
I did some digging in https://github.com/mui-org/material-ui/issues/22351#issuecomment-778660214, this seems to fix the issue:

```diff
diff --git a/packages/react-swipeable-views/src/SwipeableViews.js b/packages/react-swipeable-views/src/SwipeableViews.js
index b25b743..4e8ea1e 100644
--- a/packages/react-swipeable-views/src/SwipeableViews.js
+++ b/packages/react-swipeable-views/src/SwipeableViews.js
@@ -763,6 +763,11 @@ So animateHeight is most likely having no effect at all.`,
       }
     }

+    // Workaround bug https://github.com/oliviertassinari/react-swipeable-views/issues/599.
+    if (this.containerNode) {
+      this.containerNode.style.WebkitTransition = WebkitTransition;
+      this.containerNode.style.transition = transition;
+    }
+
     const containerStyle = {
       height: null,
       WebkitFlexDirection: axisProperties.flexDirection[axis],
```

**Comment by yanickrochon** [comment]
I have the exact problem as well. The initial element has this style applied to it :

```css
element.style {
    flex-direction: row;
    transition: all 0s ease 0s;
    direction: ltr;
    display: flex;
    will-change: transform;
    transform: translate(-100%, 0px);
}
```

After the first transition, the `transition` is set correctly

```css
element.style {
    flex-direction: row;
    transition: transform 0.35s cubic-bezier(0.15, 0.3, 0.25, 1) 0s;
    direction: ltr;
    display: flex;
    will-change: transform;
    transform: translate(0%, 0px);
}
```
